- name: Create the WATDIV directory
  file:
    path: "{{ target_dir }}/datasets/watdiv"
    state: directory

- name: Check for the WATDIV Generator
  stat:
    path: "{{ target_dir }}/datasets/watdiv/generator/bin/Release/watdiv"
  register: generator

- include: install-generator.yaml
  when: not generator.stat.exists

- include: run-generator.yaml

# - name: Download WATDIV OPTIONAL queries
#   get_url:
#     url: "{{ hobbit_url }}/watdiv.txt"
#     dest: "{{ target_dir }}/datasets/watdiv/queries.txt"

# - name: Download WATDIV OPTIONAL queries multiple instances
#   get_url:
#     url: "{{ hobbit_url }}/watdiv_instances.zip"
#     dest: "{{ target_dir }}/datasets/watdiv/watdiv_instances.zip"

# - name: Create directory for WATDIV OPTIONAL queries multiple instances
#   file:
#     path: "{{ target_dir }}/datasets/watdiv/watdiv_instances/"
#     state: directory

# - name: Unzip WATDIV OPTIONAL queries multiple instances
#   unarchive:
#     src: "{{ target_dir }}/datasets/watdiv/watdiv_instances.zip"
#     dest: "{{ target_dir }}/datasets/watdiv/"
#     remote_src: yes