iguana_http_connections:
  - number: 1
  - number: 4
  - number: 8
  - number: 16
  - number: 32
iguana_time_limit: 3600000
iguana_query_mixes_limit: 30
iguana_query_timeout: 180000
tentris_timeout: "{{ (iguana_query_timeout * 0.001 + 1) | int }}"
neo4j_timeout: "{{ (iguana_query_timeout * 0.001 + 1) | int }}"

tentris_gql_versions:
  - TentrisLJ
  - TentrisLJBase

tentris_sparql_versions:
  - TentrisLJ

graphql_services_http:
  - name: Neo4j
    connection_url: http://localhost:7474/db/neo4j/tx/commit
    iguana_worker: CypherWorker

sparql_triplestores_http:
  - name: Fuseki
    connection_url: http://localhost:3030/%d/sparql
  - name: Blazegraph
    connection_url: http://localhost:9999/blazegraph/sparql
  - name: Virtuoso
    connection_url: http://localhost:8890/sparql
  - name: GraphDB
    connection_url: http://localhost:7200/repositories/%d
